resilience4j:
  circuitbreaker:
    instances:
      mercadoLibreApi:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
  retry:
    instances:
      mercadoLibreRetry:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout



spring:
  application:
    name: coupon
  
  data:
    mongodb:
      uri: "mongodb+srv://alanguevaraco:P70wkLmUzD3YfMnB@mercado-libre-coupon.aikkox3.mongodb.net/meli-cupon?retryWrites=true&w=majority&tls=true"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

ml:
  app:
    client_id: 6437969218645616
    client_secret: 4bllPbVNJcRA1QZX4PxYyJZHcDF9aZQY
    redirect_uri: https://dashboard.render.com/